### ISSUE TITLE
how can i custom my own svg?

### ISSUE THREAD

**Issue by 2293256828** [mallowigi/a-file-icon-idea#223]
**Describe the bug**
after my hard ps,i got my svg, but when i try to custom my icon, after i click the 'apply',it just becomes the default icon rather than my custom icon, do u no why?

**Environment**
IntelliJ IDEA 2020.3.4 (Ultimate Edition)
Build #IU-203.8084.24, built on April 27, 2021
Licensed to IntelliJ IDEA Evaluator
Expiration date: October 28, 2021
Runtime version: 11.0.10+8-b1145.96 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Non-Bundled Plugins: com.mallowigi, io.zhile.research.ide-eval-resetter, GsonFormatPlus, com.dubreuia, com.alibaba.p3c.smartfox, com.linsage, org.sonarlint.idea, org.mapstruct.intellij, com.baomidou.plugin.idea.mybatisx

**Screenshots**
this is what i want (i have tried to adjust the size and apply)
![image](https://user-images.githubusercontent.com/74256608/135055776-04e4aa25-8dfe-46de-8a9d-f2172928d309.png)

this is what i got
![image](https://user-images.githubusercontent.com/74256608/135055740-be46c4bd-5e16-4dd4-a09f-36c2a0c8ea61.png)

**Comment by 2293256828** [comment]
by the way, i can not find your svg on my computer, can you provide a path to find it so that i could use your icon?
because when i use the icon on my computer ,it hints that org.apache.batik.bridge.BridgeException: NO_EXTERNAL_RESOURCE_ALLOWED

**Comment by 2293256828** [comment]
if i want to give all controller a icon, how should i
use my patter?

**Comment by mallowigi** [comment]
Can you show me how you configured your custom association?

**Comment by 2293256828** [comment]
after i upversion ,i now have just only one problem left, i guess the probelms above has been solved in your new version ,
now i have just only one problem is that how should i write my pattern regex, look that:
![image](https://user-images.githubusercontent.com/74256608/135106624-36c59ffb-b283-4b48-b9d7-e22b2a15dd13.png)
how can i change the controller to a icon and service to anthor with even i can not change all the .java icon? could u teach me how should i write my regex pattern if i want all the .java file with 'Controller' End have a special icon?

**Comment by mallowigi** [comment]
I suppose you could write `.*[cC]ontroller\.java$` ?

**Comment by 2293256828** [comment]
it doesnot matter,did u  write stably the .java icon? 
![image](https://user-images.githubusercontent.com/74256608/135110160-48a8802f-d0d0-4efb-a99a-e4741684ff79.png)

**Comment by mallowigi** [comment]
Ok, for Java (and Kotlin, Scala, etc...) it's another story, because it shows the "PSI Icon" (e.g. the icon for the type of component: class, interface, etc). Sadly, these PSI Icons cannot be modified easily because they are part of the "UI Icons", as opposed of the other file types. For your custom association to be recognized, you would need to be in a non-java project, as they would replace the default "coffee icon"

I suppose there is a way to customize PSI Icons but this would require custom associations for UI Icons, and it's not on the roadmap for now.

Another possibility would be the "enforce icons" feature that I need to work on, which is on the roadmap, but I have no idea when I'll start working on it.

For the rest (xml files), they should be working

**Comment by 2293256828** [comment]
ok,thanks, do u know mybatis-x plugins?,they have done this to interface,
![image](https://user-images.githubusercontent.com/74256608/135112330-8c099196-e194-48ba-8a55-2363287c0d13.png)
may be helpful for u

**Comment by mallowigi** [comment]
interesting, i'll take a look. They probably implemented a SVGParser just like I did, but maybe there's more to it.
