### ISSUE TITLE
In Goland test files are not applying icon

### ISSUE THREAD

**Issue by hrozan** [mallowigi/a-file-icon-idea#258]
**Describe the bug**

When a open the project tab the `_test.go` icons is the default one. I tried to change the regex in the Association menu, but nothing seems to work.

**To Reproduce**

1. Open the project tab in Goland
2. Navigate to a `*_test.go` file

**Expected Behavior**

The test icon should be the same of the association menu.

**Environment**

__OS:__ Linux 5.15.7-1-MANJARO x86_64 GNU/Linux 
__Product:__ Goland 2021.3.2
__Plugins Version:__ 
- Atom Material Icons 53.0.0
- Material Theme UI 6.12.2

**Screenshots**

![image](https://user-images.githubusercontent.com/16821536/147782092-52a6ff5a-5f6e-4d49-9791-bd48f80a99db.png)

![image](https://user-images.githubusercontent.com/16821536/147782132-2aaf34e7-9f0c-4a27-bacd-28c88ca4ee78.png)

![image](https://user-images.githubusercontent.com/16821536/147782627-668dc158-6b8b-488e-88c2-e693505450c6.png)

**Comment by hrozan** [comment]
Awesome work in this plugin! I really love using it.

**Comment by hrozan** [comment]
I was doing some test and if I change the file name to `*.test.go` or `*_spec.go` which are valid names according to the regex, the icon works.
![image](https://user-images.githubusercontent.com/16821536/147787329-01e804a3-3daa-47a1-8db4-1685ad1be115.png)

The problem is that this are not valid files to `go test` command 😞, I think the problem is with the `*_test.go` case only. Some time a go this was working...

**Comment by mallowigi** [comment]
You have the same problem Python files have, e.g. one of the Go plugins override the icons provided by the plugin to supply their own. Here in this case it involves *_test.go files, which is why it has the gopher icon instead of the test or the -GO icon

Please follow https://github.com/mallowigi/a-file-icon-idea/issues/125 , I've started working on a refactor to overcome this issue, but at the moment I'm on project hiatus due to other projects dragging around.

**Comment by hrozan** [comment]
Thanks! I will follow the other issue.
