### ISSUE TITLE
Implementing a PSI visualisation in Typescript

### ISSUE THREAD

**Issue by Vark-aN** [mallowigi/a-file-icon-idea#318]
Hello 👋
This is my first issue on a public project 😅
I hope to do well and that I don't say anything stupid.. haha

**Is your feature request related to a problem? Please describe.**
I've been using Material Icons for about a year now and I'm very happy with it, it's a nice change from the horrible things that are offered by default when you install the IDE.

However, as someone who codes a lot in PHP & Typescript, I'm a bit disappointed with the PSI support for TypeScript. 
An abstract class is not supported on the TypeScript side while on the PHP side it is... and the visual when you manipulate a lot of files, it's quite important, as much as the name of the files!

Do you think PSI integration is possible for Typescript? 🥺

**Describe the solution you'd like**
I don't think there is any need to reinvent the world for this kind of thing, if I take what is done on the PHP side, we should adapt the colour to the TypeScript graphic charter 

<img width="300" alt="psiIcons" src="https://user-images.githubusercontent.com/68712292/191612802-651b0ff6-d647-4a74-a0da-59884273be70.png">

**Describe alternatives you've considered**
Well, after reading a bit of documentation, the only possible alternative would be to import icons and have the selection done on the file name, but that seems to me to be an overkill solution because there is already a PSI system for PHP and it would be enough to transpose it to other languages. 

**Additional context**
Euh.. ❤️🇫🇷

**Comment by Unthrottled** [comment]
I was curious about this, so I looked into it a bit.

Looks like what icon gets dealt is probably dependent on what the language plugin parses/recognizes.

I created a Kotlin file and added a single abstract class into it, and also added a empty Kotlin file. When the IDE first starts up both files are recognized as a plain Kotlin file (PsiFile). However, later on, the file with the abstract class gets recognized as a class (KtClass).

I did the same thing with typescript, and both of the files remain recognized as JSFileImpl (which is a PsiFile). Looks like the Typescript support (atleast for the bundled intellij ultimate) doesn't treat them the same, so they all get the same file icon. So I guess without having special names for the file & creating an association, we'd need the typescript language plugin to recognize the file with an abstract class as another type of PsiElement.

That being said, I'm just an outsider looking in at a black box and assuming things work the way they do, so take it with a grain of salt.

**Comment by mallowigi** [comment]
This is something I wanted from day one, but alas it's not something available out of the box, and if some implementation is needed, it's definitely not something that should be done within the scope of this plugin.

In my opinion, it wouldn't make sense in JavaScript as files can be represented in many ways:
- IIFE
- module.exports
- class(es)
- angular module
- list of exported elements
- etc

Also, it depends on the framework/libraries. The contents of a file can vary a lot, it could be `eslint.js`, `gulpfile.js`, `app.js`, `server.js`... and don't get me started on the index.js which can serve many purposes.

Truly, to bother parsing the files in order to detect what kind of psi elements are in there are most of the time completely useless. It could make sense in well-defined frameworks such as Angular or Nest, but it's an exception to the rule. Relying on the extension is usually the rule of thumb here, the aforementioned frameworks advise on that, and other frameworks recommend to do the same (Redux, RxJS, etc). But its' seldom enforced and still not enough reason to do so.

BTW, next time please open a **Discussion** for this, not a bug. Thanks
