### ISSUE TITLE
TypeScript files have RxJS icons

### ISSUE THREAD

**Issue by lsalazarm99** [mallowigi/a-file-icon-idea#341]
**Describe the bug**
TypeScript files have RxJS icons. Even after using the "Reset Default Associations" buttons, they still have RxJS icons.

The pattern for RxJS icons is `rxjs\.[jt]s$`. The pattern for TypeScript is `.*\.(ts|tslint)$`.

**To Reproduce**
1. Install the plugin.
2. Create a TS file.

**Expected Behavior**
TypeScript files have TypeScript icons.

**Environment**
WebStorm 2022.3.1
Build #WS-223.8214.51, built on December 20, 2022
Runtime version: 17.0.5+1-b653.23 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.markskelton.one-dark-theme (5.7.2)
    ru.adelf.idea.dotenv (2022.3)
    com.almightyalpaca.intellij.plugins.discord (1.11.0)
    com.mallowigi (84.0.0)

**Comment by mallowigi** [comment]
This is probably because you have a parent folder from one of the usual rxjs folders: actions, entities...

Correct me if I'm wrong. And you can disable it in the custom associations.

**Comment by lsalazarm99** [comment]
Well, even the TypeScript files in the root of my project (which is not named as any RxJS folder) have the RxJS icon. 😞

Thanks for the workaround too!

**Comment by azappa** [comment]
I've updated the plugin today but seems the bug still be there.

**Comment by mallowigi** [comment]
Can you check in the custom associations if the aforementioned faulty association is still there?

**Comment by IGassmann** [comment]
This is also happening because all my local repositories are located in the directory: `/Users/[username]/Repositories/`.

@mallowigi, the solution might be to exclude from the pattern the parent path segments that are outside the project, and only apply it on project paths.

My TypeScript project is located at: `/Users/[username]/Repositories/my-typescript-project/`.
My TypeScript file is at the path: `/Users/[username]/Repositories/my-typescript-project/src/index.tsx`.

The "NgRx Repositories Files" pattern matching: .`*/(repos?|repository|repositories)/.*\.[tj]sx?$` and is applied to the full absolute path of where my TypeScript file located.

Instead of applying the pattern on:

`/Users/[username]/Repositories/my-typescript-project/src/index.tsx`.

...applied it on:

`/src/index.tsx`.

**Comment by mallowigi** [comment]
Aha good catch... currently it looks in all subfolders of the parent pattern... 

It's a bit problematic to restrict the scope, JB doesn't have a concept of scope to begin with. But one solution would be to restrict the children. 

So instead of `/(repos?|repository|repositories)/.*\.[tj]sx?$` it would be more like `/(repos?|repository|repositories)/[^/]*\.[tj]sx?$`

**Comment by mallowigi** [comment]
But to do so would require to change all parent folder patterns... if you could do a PR that would be truly helpful ^^
