### ISSUE TITLE
Debugger and Run Icons barely visible in IntelliJ New UI

### ISSUE THREAD

**Issue by javiergarber** [mallowigi/a-file-icon-idea#430]
**Describe the bug**

"Debugger" and "Run" are icons barely visible in new UI when running or debugging a project. I'm not sure but this is something that probably happens in other Jetbrains products
**To Reproduce**

1. Change IntelliJ to the New UI
2. Run or Debug a project

**Expected Behavior**

The icons should be more visible with the background
**Environment**

Linux
IntelliJ IDEA 2023.2.4 (Ultimate Edition)
Build #IU-232.10203.10, built on October 24, 2023
Plugin version 93.1.0

**Screenshots**

![How the currently look](https://github.com/mallowigi/a-file-icon-idea/assets/45274337/fbeb8eb6-426e-4726-9f95-22a5962f91ff)
![How, in my opinion, should look alike](https://github.com/mallowigi/a-file-icon-idea/assets/45274337/22ee0db6-381b-43f4-83d9-8be3d039fc5b)

I did the recommended change by just enabling the "monochrome Icons" option, but that disables the colors of all the icons in the UI which is not a good approach.

**Comment by KarimElsayad247** [comment]
I have the same problem. Glad I'm not alone.

It's not just those even while running, "More Options" buttons is also barely visible.
![image](https://github.com/mallowigi/a-file-icon-idea/assets/43252094/f0b85597-840f-4f41-a712-f72d9a917688)

**Comment by KarimElsayad247** [comment]
For now I decided to disable the "Enable UI Icons" options, not a big loss for me since I'm in for the directory icons anyway.

**Comment by mallowigi** [comment]
The background color of the buttons is set by the theme. The icons are colorful by design and are not changing anytime soon.

Since there is no option to "override" specific icons, the better option would be to ask the theme author to provide an option to have "gray button" instead of colorful. You can also enable monochrome icons, disable UI icons, or just get used to it, it's not a big deal.

In the future there is a plan to allow specific overrides but I'm far from having the time to allocate on my projects, so this will wait.

PS: You are also free to contribute and implement your own creative solutions.
