### ISSUE TITLE
Custom Folder Association only Partially reflect in Project File tree

### ISSUE THREAD

**Issue by alexwolf22** [mallowigi/a-file-icon-idea#91]
I tried adding a custom file association for the directory `handlers` and it seemed to upload and be recognized by the plugin fine.

However in the project view it only partially converted the image, to a grey folder box, instead of the full icon I uploaded (pink highlights in photo below)

Weirdly it rendered successfully in the find usages tool at the bottom of the screen (green highlighted in photo).

Any ideas on what could be causing the problem?

![Screen Shot 2020-06-03 at 2 52 38 PM](https://user-images.githubusercontent.com/17020909/83677537-52c6b900-a5aa-11ea-8fb5-eb6f3a6d031f.png)

**Comment by mallowigi** [comment]
Nice catch! It's because of the "hollow folders" feature. Usually for native associations two icons are provided: the normal one and the hollow one. However in this case since you can only provide the normal icon, it doesn't find the hollow version of it and therefore returns the default one.

I have to figure out how to prevent the hollow folders to return an hollow icon for custom icons.

**Comment by mallowigi** [comment]
If you don't care about the Hollow folders feature though I'd suggest to disable it.

**Comment by alexwolf22** [comment]
Folder icon seems to be working even with hollow folders enabled. 

Unsure if you pushed the update already or it was from me updating PyCharm. Thanks for looking into this!

![image](https://user-images.githubusercontent.com/17020909/85912749-f77c9500-b7fc-11ea-8870-01db87ec3c0f.png)
